In [3]:
import numpy as np
x = np.array([1,1,1])
while ((- 2*x[0] -x[1] -x[2] -np.log(x[0]))**2 + (- 2*x[1] -x[0] -x[2] -np.log(x[1]))**2 + (- 2*x[2] -x[0] -x[1] -np.log(x[2]))**2 >= 1e-12):
    j = np.array([[-2-1/x[0],-1,-1],[-1,-2-1/x[1],-1],[-1,-1,-2-1/x[2]]])
    x = x- np.linalg.inv(j)@np.array([1- 2*x[0] -x[1] -x[2] -1-np.log(x[0]),1- 2*x[1] -x[0] -x[2] -1-np.log(x[1]),1- 2*x[2] -x[0] -x[1] -1-np.log(x[2])])
    print(x)

[0.2 0.2 0.2]
[0.28993755 0.28993755 0.28993755]
[0.30045431 0.30045431 0.30045431]
[0.30054196 0.30054196 0.30054196]
