In [6]:
import numpy as np
def deter(ar):
    ar=np.array(ar)
    rows,columns=np.shape(ar)
    if(rows==2):
        return((ar[0,0]*ar[1,1])-(ar[0,1]*ar[1,0]))
    else:
        f=ar[0,0]*deter(ar[1:,1:])
        for i in range(1,rows-1):
            f+=((-1)**(i%2))*deter(np.concatenate((ar[1:,0:i],ar[1:,i+1:]),axis=1))*ar[0,i]
        f+=ar[0,rows-1]*deter(ar[1:,:rows-1])*((-1)**(rows-1))
        return f
                            

In [7]:
import numpy as np
def user_input():
    a=int(input("Enter the number of rows or columns"))
    ar=np.zeros((a,a))
    for i in range(a):
        for j in range(a):
            ar[i][j]=int(input("Enter number"))
    return ar

    

In [8]:
def main():
    ar=user_input()
    print(deter(ar))

In [4]:
main

<function __main__.main()>

In [10]:
main()

Enter the number of rows or columns 4
Enter number 1
Enter number 3
Enter number 1
Enter number 4
Enter number 3
Enter number 9
Enter number 5
Enter number 15
Enter number 0
Enter number 2
Enter number 1
Enter number 1
Enter number 0
Enter number 4
Enter number 2
Enter number 3


-4.0


In [7]:
import numpy as np
ma = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.transpose(ma))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
