In [3]:
'''Question 1 (Self Did) Mananananana'''
import numpy as np 
X = np.random.randint(-9,10,(5,5))
A = X@X.T + np.identity(X.shape[1])
c = np.random.randint(-9,10,5)
def g(A,c,x):
    return A@x + c
#I make an initial guess 
x = np.random.randint(1,100,5)
d = -g(A,c,x)
count = 0 
z1 = False
while np.linalg.norm(g(A,c,x)) >= 1e-6:
    xc = x.copy()
    x = x - (np.dot(g(A,c,x),d)*d)/(d.dot(A.dot(d)))
    print(x)
    if count%5 < 4: 
        d = -g(A,c,x) + ((np.dot(g(A,c,x),g(A,c,x)))/(np.dot(g(A,c,xc),g(A,c,xc))))*d
        count = count + 1
    else:
        d = -g(A,c,x)
        count+=1
        
    if count > 5:
        print("Solution does not converge in 5 steps")
        z1 = True
        
if not z1:
    print("Verified solution converges in 5 steps")

[ 60.96492829  62.53806143 -38.25331702  11.46275439  81.1083221 ]
[ 48.37328968  66.58472526 -56.48799583  -5.90029739  59.02012109]
[ 49.20612092  55.9410389  -53.30895727 -27.08729187  55.84961292]
[ 25.87073414  51.91641218 -34.18692048 -27.77206302  50.21284917]
[ 0.45829735  0.80812315 -0.51410652 -0.41851797  0.78931527]
Verified solution converges in 5 steps


In [2]:
import numpy as np 
z1=False
for i in range(100): 
    X=np.random.randint(-9,10,25).reshape(5,5)
    A= X@X.T+ np.diag([1,1,1,1,1])
    c=np.random.randint(-9,10,5)
    z=False
    g= lambda A,c,x: A@x+c
    x=np.random.randint(0,100,5)
    d=-g(A,c,x)
    count=0
    while np.linalg.norm(g(A,c,x))>1e-6:
        x_p=x.copy()
        x=x-((g(A,c,x).dot(d))/(d.dot(A.dot(d))))*d
        #print(x)
        if count%5<4 :
            d=-g(A,c,x) + (g(A,c,x).dot(g(A,c,x))/ g(A,c,x_p).dot(g(A,c,x_p))) *d
            count+=1
        else:
            d=-g(A,c,x)
            count+=1
        
    if count>5:
        print("No, solution doesn't converge in 5 step for A,c \n",A,c,"\nTook",count,"Steps")
        z1=True
        




    
if not z1:
    print("Verified that all solution converges in 5 steps")


        

    
    

No, solution doesn't converge in 5 step for A,c 
 [[ 98  -7 -74 -46  14]
 [ -7  16  21   3 -43]
 [-74  21  96  48 -68]
 [-46   3  48 239 -12]
 [ 14 -43 -68 -12 135]] [5 6 2 4 7] 
Took 10 Steps
No, solution doesn't converge in 5 step for A,c 
 [[312 -50 -58 -66 -78]
 [-50 102 -27 -69 -42]
 [-58 -27 104  -4  38]
 [-66 -69  -4 144  60]
 [-78 -42  38  60 102]] [-6 -6 -8  7 -1] 
Took 10 Steps
No, solution doesn't converge in 5 step for A,c 
 [[ 216    4  -86   40 -105]
 [   4   22   24  -20   16]
 [ -86   24   92  -47   70]
 [  40  -20  -47  154   -3]
 [-105   16   70   -3  191]] [ 0  1 -9 -2 -1] 
Took 10 Steps
No, solution doesn't converge in 5 step for A,c 
 [[ 65  34  -2  43  56]
 [ 34 124 -33  12  59]
 [ -2 -33 215 -26 -54]
 [ 43  12 -26 129 109]
 [ 56  59 -54 109 175]] [ 3 -3 -4  6 -3] 
Took 10 Steps
No, solution doesn't converge in 5 step for A,c 
 [[153 -22 -58  63  61]
 [-22  59  22 -56   9]
 [-58  22 106  16 -90]
 [ 63 -56  16 114 -13]
 [ 61   9 -90 -13 156]] [ 0  7  7 -7  1] 
Took