In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st

np.random.seed(100)

data = pd.read_csv("data3.csv",header=None)
#print(data)
x1=np.sort(data.iloc[:,0])
x2=np.sort(data.iloc[:,1])
x3=np.sort(data.iloc[:,2])

mle1=np.mean(x1)/9
mle2=np.mean(x2)/9
mle3=np.mean(x3)/4
print(mle1, mle2, mle3)


smp1=np.random.binomial(9,mle1,10000)
smp1=np.sort(smp1)
smp2=np.random.binomial(9,mle1,10000)
smp2=np.sort(smp2)
smp3=np.random.negative_binomial(4,0.573065,10000)
smp3=np.sort(smp3)

uval1, c1 = np.unique(x1, return_counts=True)
uval2, c2 = np.unique(x2, return_counts=True)
uval3, c3 = np.unique(x3, return_counts=True)
us1, csm1 = np.unique(smp1, return_counts=True)
us2, csm2 = np.unique(smp2, return_counts=True)
us3, csm3 = np.unique(smp3, return_counts=True)
print(uval3,c3)
print(us3, csm3)

f1 = c1/np.sum(c1)
f2 = c2/np.sum(c2)
f3 = c3/np.sum(c3)
fsm1 = csm1/np.sum(csm1)
fsm2 = csm2/np.sum(csm2)
fsm3 = csm3/np.sum(csm3)

cd1=np.cumsum(f1)
cd2=np.cumsum(f2)
cd3=np.cumsum(f3)
cdsm1=np.cumsum(fsm1)
cdsm2=np.cumsum(fsm2)
cdsm3=np.cumsum(fsm3)

pow1=0
D1=np.max(np.abs(cd1 - cdsm1)) * len(x1)**0.5
for i in range(1,10000):
    pow1+= np.exp(-((2*i - 1)**2 * (np.pi)**2)/(8 * D1**2))
pp1 = 1 - (((2*np.pi)**0.5)/D1)*(pow1)



print(np.max(np.abs(cd1 - cdsm1)),pp1)
print(np.max(np.abs(cd2 - cdsm2)))
print(np.max(np.abs(cd3 - cdsm3)))


Dn1, p1 = st.kstest(x1,smp1)
Dn2, p2 = st.kstest(x2,smp2)
Dn3, p3 = st.kstest(x3,smp3)
print(Dn1,p1)
print(Dn2,p2)
print(Dn3,p3)


#plt.plot(x1,y,x2,y,x3,y,smp,y)
# plt.show()

0.6117444444444444 0.4410777777777778 0.714525
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17] [1196 1958 1947 1696 1201  776  502  331  175  100   53   29   14   11
    4    2    3    2]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 19] [1117 1805 1927 1667 1255  896  579  326  171  122   67   28   20   11
    4    1    2    1    1]
0.008500000000000008 0.46531922022515737
0.39879999999999993


ValueError: operands could not be broadcast together with shapes (18,) (19,) 

In [10]:
import numpy as np
import pandas as pd
import scipy.stats as st
np.random.seed(100)

def ks_test(sample1, sample2):
    # Sort the samples
    sample1_sorted = np.sort(sample1)
    sample2_sorted = np.sort(sample2)
    
    # Calculate the CDFs of the samples
    cdf1 = np.searchsorted(sample1_sorted, sample1, side='right') / len(sample1_sorted)
    cdf2 = np.searchsorted(sample2_sorted, sample1, side='right') / len(sample2_sorted)
    
    # Calculate the maximum absolute difference between the CDFs
    ks_statistic = np.max(np.abs(cdf1 - cdf2))
    return ks_statistic

data = pd.read_csv("data3.csv",header=None)
#print(data)
x1=data.iloc[:,0]
x2=data.iloc[:,1]
x3=data.iloc[:,2]

mle1=np.mean(x1)/9
mle2=np.mean(x2)/9
mle3=np.mean(x3)/4

smp1=np.random.binomial(9,mle1,10000)
smp2=np.random.binomial(9,mle1,10000)
smp3=np.random.negative_binomial(4,0.573065,10000)


print(ks_test(x1,smp1))
print(ks_test(x2,smp2))
print(ks_test(x3,smp3))

Dn1, p1 = st.kstest(x1,smp1)
Dn2, p2 = st.kstest(x2,smp2)
Dn3, p3 = st.kstest(x3,smp3)
print("scipy",Dn1,p1)
print("scipy",Dn2,p2)
print("scipy",Dn3,p3)


0.008500000000000008
0.39879999999999993
0.028100000000000014
scipy 0.0085 0.8629266196033867
scipy 0.3988 0.0
scipy 0.0281 0.0007439049103464535


In [6]:
import numpy as np
import pandas as pd
import scipy.stats as st

data = pd.read_csv("data3.csv",header=None)
#print(data)
x1=np.sort(data.iloc[:,0])
x2=np.sort(data.iloc[:,1])
x3=np.sort(data.iloc[:,2])

mle1=np.mean(x1)/9
mle2=np.mean(x2)/9
mle3=np.mean(x3)/4
#print(mle1, mle2, mle3)


smp1=np.random.binomial(9,mle1,10000)
smp1=np.sort(smp1)
smp2=np.random.binomial(9,mle1,10000)
smp2=np.sort(smp2)

print(ks_test(x1,smp1))
print(ks_test(x2,smp2))

print(st.kstest(x1,smp1))
print(st.kstest(x2,smp2))

[1.0e-04 3.8e-03 3.8e-03 ... 1.0e+00 1.0e+00 1.0e+00]
0.015000000000000013
[0.0057 0.0057 0.0057 ... 1.     1.     1.    ]
0.39249999999999996
KstestResult(statistic=0.015, pvalue=0.21055778388518093, statistic_location=5, statistic_sign=1)
KstestResult(statistic=0.3925, pvalue=0.0, statistic_location=4, statistic_sign=1)


In [7]:
help(np.searchsorted)

Help on function searchsorted in module numpy:

searchsorted(a, v, side='left', sorter=None)
    Find indices where elements should be inserted to maintain order.
    
    Find the indices into a sorted array `a` such that, if the
    corresponding elements in `v` were inserted before the indices, the
    order of `a` would be preserved.
    
    Assuming that `a` is sorted:
    
    ======  ============================
    `side`  returned index `i` satisfies
    ======  ============================
    left    ``a[i-1] < v <= a[i]``
    right   ``a[i-1] <= v < a[i]``
    ======  ============================
    
    Parameters
    ----------
    a : 1-D array_like
        Input array. If `sorter` is None, then it must be sorted in
        ascending order, otherwise `sorter` must be an array of indices
        that sort it.
    v : array_like
        Values to insert into `a`.
    side : {'left', 'right'}, optional
        If 'left', the index of the first suitable location found is g