In [15]:
import numpy as np
X = np.random.randint(-9,10,(5,5))
A = X@X.T + np.identity(X.shape[1])
c = np.random.randint(-9,10,5)
def g(A,c,x):
    return A@x + c
#I make an initial guess 
x = np.random.randint(1,100,5)
evec = np.linalg.eig(A)[1]
print(evec)
count = 0
gk=g(A,c,x)
dk=(evec[0])

while (np.linalg.norm(gk) >= 1e-6):
    al=(np.dot(gk,dk))/(dk.dot(A.dot(dk)))
    x = x + al*dk
    if count<=4:
        print(count)
        count+=1 
        dk=np.array(evec[count])
    
    print(x)

[[-0.24640576  0.60171324  0.09050187 -0.75315259 -0.04237887]
 [ 0.64800782  0.2668964  -0.47826803 -0.02650297 -0.52859197]
 [-0.23516176  0.71019135  0.08542232  0.65683827 -0.03992129]
 [-0.10428161  0.10310547 -0.76972195 -0.01095657  0.62121065]
 [ 0.67319712  0.22738734  0.40410426 -0.02240997  0.57558507]]
0
[ 16.7034643  148.88922993  94.55653727   0.79287343  62.99327188]
1
[-77.51068762 110.08504053 164.0921436    4.64615242 139.84549956]
2
[-111.99003385  214.21308141  176.61673834  100.95158202  133.99225192]
3
[-115.57562929  217.75823693  150.15079056  100.57485382  155.35182036]
4


IndexError: index 5 is out of bounds for axis 0 with size 5