In [1]:
import numpy as np
help(np.linalg.svd)

Help on function svd in module numpy.linalg:

svd(a, full_matrices=True, compute_uv=True, hermitian=False)
    Singular Value Decomposition.
    
    When `a` is a 2D array, and ``full_matrices=False``, then it is
    factorized as ``u @ np.diag(s) @ vh = (u * s) @ vh``, where
    `u` and the Hermitian transpose of `vh` are 2D arrays with
    orthonormal columns and `s` is a 1D array of `a`'s singular
    values. When `a` is higher-dimensional, SVD is applied in
    stacked mode as explained below.
    
    Parameters
    ----------
    a : (..., M, N) array_like
        A real or complex array with ``a.ndim >= 2``.
    full_matrices : bool, optional
        If True (default), `u` and `vh` have the shapes ``(..., M, M)`` and
        ``(..., N, N)``, respectively.  Otherwise, the shapes are
        ``(..., M, K)`` and ``(..., K, N)``, respectively, where
        ``K = min(M, N)``.
    compute_uv : bool, optional
        Whether or not to compute `u` and `vh` in addition to `s`.  True
  

In [2]:
a = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)
b = np.random.randn(2, 7, 8, 3) + 1j*np.random.randn(2, 7, 8, 3)
print(a)

[[ 1.11171408+0.13237774j  0.33528296+1.66155478j -2.39110732-0.18288553j
   0.09800611-3.02674484j -0.75155347-0.47008354j -0.38320358-0.12658101j]
 [-2.26843874-0.51905912j -0.64448344+1.80006646j -0.68446942-1.26153598j
   0.64651048+1.31302463j  2.07333662-1.04336333j -1.00623315+1.06831353j]
 [ 0.23087789+1.37407835j -0.34956968-0.91149615j -0.45851325+1.11363889j
  -0.9649158 -0.9464303j   0.18555594+0.27547215j  1.10293215+0.19070091j]
 [-0.29918315-0.17190537j  1.31051381-0.57505101j  1.17486169-0.25480981j
   1.27278518-0.50584076j  0.75003048-0.55253252j  0.2990906 -0.76169455j]
 [-0.84846544+1.302319j    0.42809928+0.32871385j  0.86986339+1.37834788j
   1.22047789-0.66494705j -0.96574489-0.10763848j -0.63963416+0.22773751j]
 [ 1.88400486-0.83757188j -0.20692551-0.07203444j -0.81552177+0.62386207j
   1.13351057+0.21438603j  0.55309283+1.32249563j -0.87248807+0.80886499j]
 [-0.9210146 -0.50905214j -0.77662021+0.86301531j -0.21146029-0.23786012j
  -1.38151057+0.14745931j -0.452

In [3]:
help(np.linalg.lstsq)

Help on function lstsq in module numpy.linalg:

lstsq(a, b, rcond='warn')
    Return the least-squares solution to a linear matrix equation.
    
    Computes the vector `x` that approximately solves the equation
    ``a @ x = b``. The equation may be under-, well-, or over-determined
    (i.e., the number of linearly independent rows of `a` can be less than,
    equal to, or greater than its number of linearly independent columns).
    If `a` is square and of full rank, then `x` (but for round-off error)
    is the "exact" solution of the equation. Else, `x` minimizes the
    Euclidean 2-norm :math:`||b - ax||`. If there are multiple minimizing
    solutions, the one with the smallest 2-norm :math:`||x||` is returned.
    
    Parameters
    ----------
    a : (M, N) array_like
        "Coefficient" matrix.
    b : {(M,), (M, K)} array_like
        Ordinate or "dependent variable" values. If `b` is two-dimensional,
        the least-squares solution is calculated for each of the `K` c

In [4]:
help(np.vstack)

Help on function vstack in module numpy:

vstack(tup, *, dtype=None, casting='same_kind')
    Stack arrays in sequence vertically (row wise).
    
    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    ``np.row_stack`` is an alias for `vstack`. They are the same function.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.
    
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
    

In [10]:
def onesol(A,b):
    A=np.array(A,dtype=float)np.array(b,dtype=float)
    m,n=np.shape(A)
    x,residuals,rank,s=np.linalg.lstsq(A,b,rcond='None')
    rankAb=np.linalg.matrix_rank(np.concatenate((A,b),axis=1))
    if(rankAb==rank):
        if(rank==np.min(m,n)):
            print("Unique solution")
            print(x)
        else:
            print("Infinite solutions")
    else:
        print("No solution")

In [11]:
A=np.array([[1,1],[2,-3]])
b=np.array([5,-4])
onesol(A,b)

UFuncTypeError: Cannot cast ufunc 'lstsq_m' input 2 from dtype('<U4') to dtype('float64') with casting rule 'same_kind'

In [1]:
import numpy as np

def onesol(A, b):
    A, b = np.array(A, dtype=float), np.array(b, dtype=float)
    m, n = np.shape(A)

    x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

    rankAb = np.linalg.matrix_rank(np.concatenate((A, b[:, None]), axis=1))

    if(rankAb==rank):
        if(rank==np.min(m,n)):
            print("Unique solution")
            return x
        else:
            print("Infinite solutions")
    else:
        print("No solution")
# Example usage
A = np.array([[1, 1], [2, -3]])
b = np.array([5, -4])
result=onesol(A, b)
print("Solution:", result)


AxisError: axis 2 is out of bounds for array of dimension 0

In [3]:
import numpy as np

def onesol(A, b):
    A, b = np.array(A, dtype=float), np.array(b, dtype=float)
    m, n = np.shape(A)

    x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

    rankAb = np.linalg.matrix_rank(np.concatenate((A, b[:, None]), axis=1))

    if (rankAb == rank and rank==min(m,n)):
        print("The system has a unique solution.")
        return x
    elif(rankAb==rank): 
        
        print("The system has infinite solutions.")
        return None
    else:
        print("System has no solution")
        return None

# Example usage
A = np.array([[1, 1], [2, -3]])
b = np.array([5, -4])
result = onesol(A, b)
print("Solution:", result)


The system has a unique solution.
Solution: [2.2 2.8]


In [10]:
import numpy as np

def onesol(A, b):
    A, b = np.array(A, dtype=float), np.array(b, dtype=float)
    m, n = np.shape(A)

    x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

    rankAb = np.linalg.matrix_rank(np.concatenate((A, b[:, None]), axis=1))

    if (rankAb == rank and rank==min(m,n)):
        print("The system has a unique solution.")
        return x
    elif(rankAb==rank): 
        print("The system has infinite solutions.")
        Q=np.linalg.eig(A.T@A)[1]
        print(f"{x}",end=" ")
        c=1
        for i in range(rank,n):
            print(f"+t{c}{Q[:,i]}",end=" ")
            c+=1
        return None
    else:
        print("System has no solution")
        print("Best fit solution is",end=" ")
        print(x)
        print("Squared error is",end=" ")
        print(residuals)
        return None


In [11]:
# Example usage
A = np.array([[1, -2, 3], [2, 1, 2], [2, -4, 6]])
b = np.array([17, 6, 34])
result = onesol(A, b)
print("Solution:", result)

The system has infinite solutions.
[ 0.9 -2.8  3.5] +t1[0.60228461 0.76376995 0.2321825 ] Solution: None


In [1]:
def twosol(A):
    import numpy as np
    e,v=np.linalg.eig(A)
    if(len(e[e<0])!=0 and len(e[e>0])!=0):
        print("Indefinite")
        c1=0,c2=0
        for i in range(len(e)):
            if(c1!=1):
                if(e[i]>0):
                    print("Positive when"+v[i])
                    c1+=1
            if(c2!=1):
                if(e[i]<0):
                    print("Negative when"+v[i])
                    c+=1
            if(c1==1 and c2==1):
                break
    elif(len(e[e>0])==len(e)):
        print(v[0])
        print("positive definite")
    elif(len(e[e<0])==len(e)):
        print(v[0])
        print("negative definite")
    elif(len(e[e>0])>0):
        print("positive semi-definite")
        c1=0,c2=0
        for i in range(len(e)):
            if(c1!=1):
                if(e[i]>0):
                    print("Positive when"+v[i])
                    c1+=1
            if(c2!=1):
                if(e[i]==0):
                    print("Zero when"+v[i])
                    c+=1
            if(c1==1 and c2==1):
                break
    elif(len(e[e<0])>0):
        print("negative semi definite")
        c1=0,c2=0
        for i in range(len(e)):
            if(c1!=1):
                if(e[i]==0):
                    print("Zero when"+v[i])
                    c1+=1
            if(c2!=1):
                if(e[i]<0):
                    print("Negative when"+v[i])
                    c+=1
            if(c1==1 and c2==1):
                break
    

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (263676112.py, line 6)

In [5]:
def sixsol(A):
    import numpy as np
    A=np.array(A,dtype=float)
    A[:,0]=A[:,0]/np.linalg.norm(A[:,0])
    for i in range(1,np.shape(A)[1]):
        k=A[:,i]
        for j in range(i):
            c=np.linalg.norm(A[:,j])
            if(c==0):
                continue
            b=A[:,j]/c
            A[:,i]=A[:,i]-k.dot(b)*b
        #print(np.linalg.norm(A[:,i]))
        A[:,i]/=np.linalg.norm(A[:,i])
    print(A)
#Example
A=[[1, 1, 2], [0, 2, -1], [1, -2, 1],[2,3,1]]
sixsol(A)







































[[ 0.40824829  0.04481107  0.82973981]
 [ 0.          0.53773286 -0.37338292]
 [ 0.40824829 -0.76178822 -0.33189593]
 [ 0.81649658  0.35848857 -0.24892194]]
