In [5]:
def LU(A):
    A = np.array(A)
    ro,co= np.shape(A)
    L,U=np.identity(ro), np.zeros((ro, co))
    
    
    if(ro!=2):
        if(A[0,0]!=0):
            v=np.array(A[:,0]/A[0,0])
            w=np.array(A[0])
            L[:,0],U[0]=v,w
            v,w=v[1:],w[1:]
            Ad=np.array(A[1:,1:])
            Ad= Ad - (np.outer(v,w))
            L[1:,1:],U[1:,1:] = LU(Ad)
            return L,U
        
        elif(np.dot(A[:,0],A[:,0])==0):
            L[1:,0],U[0]=A[1:,0],A[0]
            L[1:,1:],U[1:,1:] = LU(A[1:,1:])
            return L,U
        """
        else:
            n=1
            while(A[0,0]==0 and n<ro):
                A[0],A[n]=A[n],A[0]
                n+=1
            v=np.array(A[:,0]/A[0,0])
            w=np.array(A[0])
            L[:,0],U[0]=v,w
            v,w=v[1:],w[1:]
            Ad=np.array(A[1:,1:])
            Ad= Ad - (np.outer(v,w))
            L[1:,1:],U[1:,1:] = LU(Ad)
            return L,U 
        """        
    else:
        v=np.array(A[:,0]/A[0,0])
        w=np.array(A[0])
        print(v)
        L[:,0],U[0]=v,w
        v,w=v[1:],w[1:]
        Ad=np.array(A[1:,1:])
        Ad= Ad - (np.outer(v,w))
        U[1,1:]=Ad
        return L,U

In [4]:
import numpy as np
A=np.array([[1,2,1],[2,3,3],[-3,-10,2]])
B=np.array([[1,-3,5],[2,-4,7],[-1,-2,1],[2,5,7]])
C=np.array([[0,-2,-2,-3],[0,-9,0,-9],[0,2,4,7],[0,-6,26,2]])
D=np.array([[ 0.30151134,0.16653821,0.91469295],
 [ 0., 0.61064012, -0.28219251],
 [ 0.30151134, -0.74942197, -0.09730776],
 [ 0.90453403,  0.19429458, -0.27246173]]).T
L,U= LU(B)
print("L:\n",L)
print("U:\n",U)
print("L@U:\n:",L@U)

[ 1. -9.]
L:
 [[ 1.   0.   0.   0. ]
 [ 2.   1.   0.   0. ]
 [-1.  -2.5  1.   0. ]
 [ 2.   5.5 -9.   1. ]]
U:
 [[ 1.  -3.   5. ]
 [ 0.   2.  -3. ]
 [ 0.   0.  -1.5]
 [ 0.   0.   0. ]]
L@U:
: [[ 1. -3.  5.]
 [ 2. -4.  7.]
 [-1. -2.  1.]
 [ 2.  5.  7.]]


In [ ]:
def inmat():
    ro = int(input("Enter row-dim: "))
    co = int(input("Enter col-dim: "))
    A = np.zeros((ro, co))

    print("Enter coefficient matrix row-wise")
    for i in range(ro):
        print(f"Elements of {i+1}th row:")
        for j in range(co):
            A[i][j] = int(input("Enter number: "))

    b, l1 = [], []    
    print("Enter 'b' vector: ")
    for i in range(ro):
        c = int(input("Enter number: "))
        b.append(c)
    b = np.array(b)


In [3]:
def LU(A):
    A = np.array(A)
    ro,co= np.shape(A)
    L,U=np.identity(ro), np.zeros((ro, co))
    
    
    if(ro!=2):
        if(A[0,0]!=0):
            v=np.array(A[:,0]/A[0,0])
            w=np.array(A[0])
            L[:,0],U[0]=v,w
            v,w=v[1:],w[1:]
            Ad=np.array(A[1:,1:])
            Ad= Ad - (np.outer(v,w))
            L[1:,1:],U[1:,1:] = LU(Ad)
            return L,U
        
        elif(np.dot(A[:,0],A[:,0])==0):
            L[1:,0],U[0]=A[1:,0],A[0]
            L[1:,1:],U[1:,1:] = LU(A[1:,1:])
            return L,U
  
    else:
        v=np.array(A[:,0]/A[0,0])
        w=np.array(A[0])
        print(v)
        L[:,0],U[0]=v,w
        v,w=v[1:],w[1:]
        Ad=np.array(A[1:,1:])
        Ad= Ad - (np.outer(v,w))
        U[1,1:]=Ad
        return L,U