In [8]:
import numpy as np

ro = int(input("Enter row-dim: "))
co = int(input("Enter col-dim: "))
A = np.zeros((ro, co))

print("Enter coefficient matrix row-wise")
for i in range(ro):
    print(f"Elements of {i+1}th row:")
    for j in range(co):
        A[i][j] = int(input("Enter number: "))

b,l1=[],[]    
print("Enter 'b' vector: ")
for i in range(ro):
    c = int(input("Enter number: "))
    b.append(c)
b=np.array(b)

Ab_aug = np.column_stack((A, b))

if(np.linalg.matrix_rank(Ab_aug) == np.linalg.matrix_rank(A)):
    print("System is consistent")
    if(np.linalg.matrix_rank(A) == co):
        sol=np.linalg.lstsq(A,b,rcond=None)[0]
        print("System has a unique sol.\n",sol)
    else:
        sol=np.linalg.lstsq(A,b,rcond=None)[0]
        v=np.linalg.eig(A.T@A)[1] #as eig of AtA gives us directly V, and not Vt (which is given by .svd()). Indexing [1] to get the eigen values ka vector
        r=np.linalg.matrix_rank(A)
        for i in range(r,len(v)):
            l1.append(v[:,i])
        print("Infinte sol\n Null sapce is\n",l1)
        l1=np.array(l1).T
        print("One of the sol\n",A@l1)
        print(f"Final answer\n {sol}", end=" ")
        for i in range(len(l1)):
            print(f" + t{i}*{l1[:,i]}", end=" ")
else:
    sol=np.linalg.lstsq(A,b,rcond=None)
    print("Inconsistent\n",sol)
    


Enter row-dim:  2
Enter col-dim:  4


Enter coefficient matrix row-wise
Elements of 1th row:


Enter number:  1
Enter number:  1
Enter number:  1
Enter number:  1


Elements of 2th row:


Enter number:  4
Enter number:  3
Enter number:  2
Enter number:  1


Enter 'b' vector: 


Enter number:  1
Enter number:  3


System is consistent
Infinte sol
 Null sapce is
 [array([ 0.18594553,  0.13607513, -0.82998685,  0.50796619]), array([ 0.49797586, -0.49396774, -0.5059921 ,  0.50198398])]
One of the sol
 [[ 0.00000000e+00 -5.55111512e-16]
 [ 2.22044605e-16  1.11022302e-15]]
Final answer
 [0.4 0.3 0.2 0.1]  + t0*[ 0.18594553  0.13607513 -0.82998685  0.50796619]  + t1*[ 0.49797586 -0.49396774 -0.5059921   0.50198398] 

IndexError: index 2 is out of bounds for axis 1 with size 2

In [26]:
A@(l1.T)

AttributeError: 'list' object has no attribute 'T'

In [1]:
#from adi
import numpy as np

m = int(input("For A; enter no. of rows: "))
n = int(input("For A; enter no. of columns: "))
A = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        A[i,j] = int(input("enter elements of A, row wise: "))

B = np.zeros((m,1))
for i in range(m):
    B[i,0] = int(input("enter elements of B: "))
print(f"A is: \n {A}")
print(f"B is \n {B}")

A_B = np.concatenate((A,B), axis = 1)
print(f"Augmented matrix, A_B is \n {A_B}")
ra, rab, ns, tm = np.linalg.matrix_rank(A), np.linalg.matrix_rank(A_B), [], []

if ra == rab:
    if ra == n:
        print(f"there is a unique solution: \n {np.linalg.pinv(A)@B}")
    else : 
        sol = np.linalg.pinv(A)@B
        v = np.linalg.svd(A)[2].T
        for i in range(ra, len(v)):
            ns.append(v[:,i])
        print(f"Null space of A is: {ns}")
        for i in range(len(ns)):
            tm.append(f"t{i+1}*{ns[i]}")
        print(f"there are infinite solutions of the form: \n {sol} + {tm}")
else:
    sol = np.linalg.lstsq(A,B,rcond=None)
    print(f"No Solution. The Best fit Solution is: \n {sol[0]} \n The sum of squared error is : \n {sol[1]}")

For A; enter no. of rows:  2
For A; enter no. of columns:  2
enter elements of A, row wise:  1
enter elements of A, row wise:  1
enter elements of A, row wise:  1
enter elements of A, row wise:  1
enter elements of B:  3
enter elements of B:  6


A is: 
 [[1. 1.]
 [1. 1.]]
B is 
 [[3.]
 [6.]]
Augmented matrix, A_B is 
 [[1. 1. 3.]
 [1. 1. 6.]]
No Solution. The Best fit Solution is: 
 [[2.25]
 [2.25]] 
 The sum of squared error is : 
 []


TypeError: lstsq() missing 2 required positional arguments: 'a' and 'b'