In [5]:
import numpy as np

def gram_schmidt(A):
    ro, co = np.shape(A)
    l2 = []

    u0 = A[:, 0] / np.linalg.norm(A[:, 0])
    l2.append(u0)

    for i in range(1, co):
        l1 = np.zeros(ro)
        for j in range(i):
            l1 += np.dot(A[:, i], l2[j]) * l2[j]
        num = A[:, i] - l1
        if (np.dot(num,num)==0):
            u=num
        else:
            u = num / np.linalg.norm(num)
        l2.append(u)

    return np.array(l2).T

A = np.array([[1, 1, 2], [0, 2, -1], [1, -2, 1],[3,2,1]])
orthogonal_basis = gram_schmidt(A)


for i in range(np.shape(orthogonal_basis)[1]):
    if(np.dot(orthogonal_basis[:,i],orthogonal_basis[:,i]) == 0):
        A[:,i] = np.delete(A,i,1)
    
print("Maximal set:")
print(A)
print("\nOrthogonal Basis:")
print(orthogonal_basis)


Maximal set:
[[ 1  1  2]
 [ 0  2 -1]
 [ 1 -2  1]
 [ 3  2  1]]

Orthogonal Basis:
[[ 0.30151134  0.16653821  0.91469295]
 [ 0.          0.61064012 -0.28219251]
 [ 0.30151134 -0.74942197 -0.09730776]
 [ 0.90453403  0.19429458 -0.27246173]]
