In [27]:
import numpy as np
a,b=(1/3**0.5),(1/2**0.5)
A=np.array([[a,0],[a,b],[a,-b]])
U=np.linalg.svd(A)[0]
m=np.shape(U)[1]

r=np.linalg.matrix_rank(A)
for i in range(r,m):
    U[:,i]=U[:,i]/np.linalg.norm(U[:,i])
    
A=np.concatenate((A,U[:,i:]),axis=1)

print(A)


[[ 0.57735027  0.         -0.81649658]
 [ 0.57735027  0.70710678  0.40824829]
 [ 0.57735027 -0.70710678  0.40824829]]


In [20]:
help(np.linalg.svd)

Help on function svd in module numpy.linalg:

svd(a, full_matrices=True, compute_uv=True, hermitian=False)
    Singular Value Decomposition.
    
    When `a` is a 2D array, and ``full_matrices=False``, then it is
    factorized as ``u @ np.diag(s) @ vh = (u * s) @ vh``, where
    `u` and the Hermitian transpose of `vh` are 2D arrays with
    orthonormal columns and `s` is a 1D array of `a`'s singular
    values. When `a` is higher-dimensional, SVD is applied in
    stacked mode as explained below.
    
    Parameters
    ----------
    a : (..., M, N) array_like
        A real or complex array with ``a.ndim >= 2``.
    full_matrices : bool, optional
        If True (default), `u` and `vh` have the shapes ``(..., M, M)`` and
        ``(..., N, N)``, respectively.  Otherwise, the shapes are
        ``(..., M, K)`` and ``(..., K, N)``, respectively, where
        ``K = min(M, N)``.
    compute_uv : bool, optional
        Whether or not to compute `u` and `vh` in addition to `s`.  True
  